export const contactContent: { [x: string]: any } = {
  PL: {
    header: 'kontakt',
    subHeader: 'Skontaktuj sie z nami',
    hAddress: 'Nasz adres',
    address: [
      'Mokry Dwór',
      'ul. Starodworska 4',
      '50-458 Wrocław',
      'NIP: 899-109-04-96',
    ],
    hPhone: 'Zadzwoń do nas',
    phones: ['+48 601 95 56 56', '+48 607 766 901', '+48 601 956 901'],
    hEmial: 'Napisz do nas',
    emails: [
      'stolarka@animo.wroclaw.pl',
      'animos.marcin@gmail.com',
      'animo@animo.wroclaw.pl',
    ],
    hOpen: 'Godziny otwarcia',
    hours: ['Poniedziałęk-Piątek', '8:00-16:00'],
    form: {
      name: 'Twoje imie i nazwisko',
      email: 'Twoje email',
      temat: 'Temat wiadomosci',
      message: 'Wiadomość',
    },
    sentMessage: 'Twoja wiadomość zostałą wysłana. Dziękujemy!',
    buttonText: 'Wyślij wiadomość',
    headerMap: 'Znajdz nas',
    subHeaderMap: 'Sprawdz jak do nas dojechać',
  },
  EN: {
    header: 'CONTACT',
    subHeader: 'Contact Us',
    hAddress: 'Address',
    address: [
      'Mokry Dwór',
      'ul. Starodworska 4',
      '50-458 Wrocław',
      'NIP: 899-109-04-96',
    ],
    hPhone: 'Call Us',
    phones: ['+48 601 95 56 56', '+48 607 766 901', '+48 601 956 901'],
    hEmial: 'Email Us',
    emails: [
      'stolarka@animo.wroclaw.pl',
      'animos.marcin@gmail.com',
      'animo@animo.wroclaw.pl',
    ],
    hOpen: 'Open Hours',
    hours: ['Monday-Friday', '8:00-16:00'],
    form: {
      name: 'Your name',
      email: 'Your email',
      temat: 'Subject',
      message: 'Message',
    },
    sentMessage: 'Your message has been sent. Thank you!',
    buttonText: 'Send Message',
    headerMap: 'Find us',
    subHeaderMap: 'Check how to get to us',
  },
};
